"""notification table changes

Revision ID: 257464f1787e
Revises: f0062014f853
Create Date: 2026-03-05 17:33:09.051559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '257464f1787e'
down_revision: Union[str, Sequence[str], None] = 'f0062014f853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('invite_token_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('invite_token', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'invite_token', ['invite_token_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'invite_token')
    op.drop_column('notifications', 'invite_token_id')
    # ### end Alembic commands ###
